// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjoyyevmdfbdcbhekisy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqb3l5ZXZtZGZiZGNiaGVraXN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4NjEwMjcsImV4cCI6MjA3ODQzNzAyN30.cf4GhTqW9A-es5-v1DTyhE-l34w3gz_DQmJBLbqTlo4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});